In [41]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_files
import re
import glob
import nltk
#nltk.download('stopwords')
nltk.download('wordnet')
import pickle
from nltk.corpus import stopwords

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nirco\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [58]:
# Read the train data
train_data = load_files(r'data', categories=['bylaws', 'credit', 'employment', 'rra', 'rsu', 'spa'])

In [63]:
X, y = train_data.data, train_data.target_names
print(y[0])

bylaws


In [18]:
# Txt preprocessing
documents = []

from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=1000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [22]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [24]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [28]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(X_train, y_train) 

y_pred = classifier.predict(X_test)



In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 89   0   0   0   0   0]
 [  1  19   0   0   0   0]
 [  0   0 281   0   1   0]
 [  0   0   0  23   2   1]
 [  0   0   0   0 435   3]
 [  0   0   1   1   1  28]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        89
           1       1.00      0.95      0.97        20
           2       1.00      1.00      1.00       282
           3       0.96      0.88      0.92        26
           4       0.99      0.99      0.99       438
           5       0.88      0.90      0.89        31

    accuracy                           0.99       886
   macro avg       0.97      0.95      0.96       886
weighted avg       0.99      0.99      0.99       886

0.9875846501128668


In [30]:
# Save model
with open('text_classifier', 'wb') as picklefile:
    pickle.dump(classifier,picklefile)

In [84]:
# Read the test data
import os

path = os.path.dirname('C:\Users\nirco\contract_classification\notebooks\test')
csv_files = glob.glob(os.path.join(path, "*.csv"))

#csv_files = glob.glob('test')

train_data = load_files(r'test')
X_test = train_data.data

# List comprehension that loads of all the files
# X_test = [pd.read_csv(x) for x in path]



SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_536/3913235730.py, line 4)

In [83]:
print(len(X_test))

0


In [35]:
# Txt preprocessing
documents = []

from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

for sen in range(0, len(X_test)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

vectorizer = CountVectorizer(max_features=1000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X_test = vectorizer.fit_transform(documents).toarray()

tfidfconverter = TfidfTransformer()
X_test = tfidfconverter.fit_transform(X_test).toarray()


ValueError: empty vocabulary; perhaps the documents only contain stop words

In [ ]:

y_pred2 = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2)) 